name: Prepare Environment

inputs:
    NAME:
        required: true
        type: string
    OPENMDAO_PIXI_ENVIRONMENT:
        required: true
        type: string
    OPENMDAO_INSTALL_FROM:
        required: true
        type: string
    OPENMDAO:
        required: true
        type: string
    SNOPT:
        required: true
        type: string
    DYMOS:
        required: true
        type: string
    PYOPTSPARSE:
        required: true
        type: string
    SSH_PRIVATE_KEY:
        required: true
    SSH_KNOWN_HOSTS:
        required: true
    SNOPT_LOCATION_77:
        required: true

    # Deprecate
    PY:
        required: true
        type: string
    NUMPY:
        required: true
        type: string
    SCIPY:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - name: Display run details
      shell: bash -l {0}
      run: |
        echo "============================================================="
        echo "Run #${GITHUB_RUN_NUMBER}"
        echo "Run ID: ${GITHUB_RUN_ID}"
        echo "Testing: ${GITHUB_REPOSITORY}"
        echo "Triggered by: ${GITHUB_EVENT_NAME}"
        echo "Initiated by: ${GITHUB_ACTOR}"
        echo "============================================================="

    - name: Create SSH key
      shell: bash -l {0}
      env:
        SSH_PRIVATE_KEY: ${{inputs.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{inputs.SSH_KNOWN_HOSTS}}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: 'Setup OpenMDAO pixi Environment'
      id: setup_pixi_environment
      uses: OpenMDAO/OpenMDAO/.github/actions/setup_openmdao_pixi@master
      with:
        environment: '${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }}'
        openmdao_install_from: '${{ matrix.OPENMDAO_INSTALL_FROM }}'
        openmdao_version: '${{ matrix.OPENMDAO }}'

    - name: Install Dymos
      if: inputs.DYMOS
      shell: bash -l {0}
      run: |
        echo "============================================================="
        echo "Activating pixi environment"
        echo "============================================================="
        eval "$(pixi shell-hook -e py313 --manifest-path=${{ env.PIXI_MANIFEST }})"
        echo "============================================================="
        echo "Install Dymos"
        echo "============================================================="
        if [[ "${{ inputs.DYMOS }}" == "dev" ]]; then
          pip install git+https://github.com/OpenMDAO/Dymos
        elif [[ "${{ inputs.DYMOS }}" == "latest" ]]; then
          pip install dymos
        else
          pip install dymos==${{ inputs.DYMOS }}
        fi

    - name: Install Tkinter
      shell: bash -l {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

    - name: Checkout Aviary
      uses: actions/checkout@v6

    - name: Install Aviary
      shell: bash -l {0}
      run: |
        echo "============================================================="
        echo "Install Aviary"
        echo "============================================================="
        python -m pip install -e .[all]

    - name: Display conda environment info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda env export --file environment.yml
        mv environment.yml ${{ inputs.NAME }}_environment.yml

    - name: 'Upload environment artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.NAME }}_environment
        path: ${{ inputs.NAME }}_environment.yml
        retention-days: 5
